# -*- coding: utf-8 -*-
"""WRITING SECTION.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PnElzCeF7oG27Uzl3GmUevQ3dnCUK6og
"""

# ============================================================================
# SCRIPT GENERATOR - GROQ API (100% FREE)
# ============================================================================

#
# SETUP:
# 1. Get free Groq API key: https://console.groq.com/
# 2. Add to Colab secrets as 'GROQ_API_KEY'
# 3. Run cells

# ============================================================================
# CELL 1: Setup and MCP Loading
# ============================================================================
!pip install feedparser
from google.colab import drive, userdata
import zipfile
import os
import glob

drive.mount('/content/drive')

MCP_DIR = "/content/drive/MyDrive/Angry Dude Scripts/mcps"
OUTPUT_DIR = "/content/drive/MyDrive/Angry Dude Scripts/drafts"
WORKING_MCP_DIR = "/content/mcps_extracted"

os.makedirs(WORKING_MCP_DIR, exist_ok=True)
os.makedirs(OUTPUT_DIR, exist_ok=True)

# Extract MCPs
zip_files = [f for f in os.listdir(MCP_DIR) if f.endswith('.zip')]
print(f"📦 Extracting {len(zip_files)} MCPs...")

for zip_file in zip_files:
    with zipfile.ZipFile(os.path.join(MCP_DIR, zip_file), 'r') as zip_ref:
        zip_ref.extractall(WORKING_MCP_DIR)
    print(f"   ✅ {zip_file}")

# Load MCPs
def load_mcp_properly(mcp_name):
    mcp_path = f"{WORKING_MCP_DIR}/{mcp_name}"
    if not os.path.exists(mcp_path):
        return {'rules': '', 'examples': []}

    mcp_data = {'rules': '', 'examples': []}

    rules_file = f"{mcp_path}/rules.txt"
    if os.path.exists(rules_file):
        with open(rules_file, 'r', encoding='utf-8', errors='ignore') as f:
            mcp_data['rules'] = f.read()

    examples_path = f"{mcp_path}/examples"
    if os.path.exists(examples_path):
        example_files = glob.glob(f"{examples_path}/*.txt")
        for ex_file in sorted(example_files)[:3]:
            with open(ex_file, 'r', encoding='utf-8', errors='ignore') as f:
                content = f.read().strip()
                if len(content) > 100:
                    mcp_data['examples'].append(content)

    return mcp_data

print("\n📂 Loading MCPs...")
mcp1 = load_mcp_properly("Talking_points_mcp")
mcp2 = load_mcp_properly("my_mcp")
mcp3 = load_mcp_properly("enhancements_mcp - Copy")
print(f"✅ Loaded: {len(mcp2['examples'])} style examples\n")


# ============================================================================
# CELL 2: Install & Setup Groq API (FREE)
# ============================================================================

!pip install -q groq

from groq import Groq
import time

# Hardcoded API keys
GROQ_API_KEY = ""  # Paste your gsk_ or setup .env
GEMINI_API_KEY = ""  # Paste your AIza... key or setup .env

print("✅ API keys loaded")

client = Groq(api_key=GROQ_API_KEY)

def generate_with_groq(prompt, max_tokens=1500):
    """Generate with Groq - uses Llama 3.3 70B"""
    try:
        chat_completion = client.chat.completions.create(
            messages=[
                {
                    "role": "user",
                    "content": prompt,
                }
            ],
            model="llama-3.3-70b-versatile",  # Updated free model (Dec 2024)
            temperature=0.9,
            max_tokens=max_tokens,
            top_p=0.95,
        )
        return chat_completion.choices[0].message.content.strip()
    except Exception as e:
        print(f"❌ Error: {str(e)[:200]}")
        return "[ERROR]"

# Test
test = generate_with_groq("Say 'GROQ READY!' in aggressive football banter style", max_tokens=100)
print(f"\n🧪 Test: {test}")
print("\n✅ Groq API ready (100% FREE)\n")


# Setup Gemini API
!pip install -q google-generativeai

import google.generativeai as genai

genai.configure(api_key=GEMINI_API_KEY)

gemini_model = genai.GenerativeModel(
    'gemini-2.5-flash',
    safety_settings=[
        {"category": "HARM_CATEGORY_HARASSMENT", "threshold": "BLOCK_NONE"},
        {"category": "HARM_CATEGORY_HATE_SPEECH", "threshold": "BLOCK_NONE"},
    ]
)

def generate_with_gemini(prompt, max_tokens=1500):
    try:
        response = gemini_model.generate_content(
            prompt,
            generation_config=genai.types.GenerationConfig(
                max_output_tokens=max_tokens,
                temperature=0.9,
                top_p=0.95,
            )
        )

        # Check if blocked and print reason
        if not response.parts:
            block_reason = "UNKNOWN"
            if hasattr(response, 'prompt_feedback'):
                feedback = response.prompt_feedback
                if hasattr(feedback, 'block_reason'):
                    block_reason = str(feedback.block_reason)
                if hasattr(feedback, 'safety_ratings'):
                    print(f"🚫 GEMINI BLOCKED - Reason: {block_reason}")
                    print(f"   Safety ratings: {feedback.safety_ratings}")
            return f"[BLOCKED BY GEMINI - {block_reason}]"

        return response.text.strip()
    except Exception as e:
        print(f"❌ Gemini Error: {str(e)[:200]}")
        return "[GEMINI ERROR]"

print("✅ Gemini API ready\n")


# ============================================================================
# CELL 3: Get Matches with FULL CONTEXT from ESPN
# ============================================================================

import requests
from datetime import datetime, timedelta
import feedparser
from bs4 import BeautifulSoup

def fetch_match_details(event_id, league_id):
    """Fetch detailed match data from ESPN summary endpoint"""
    detail_url = f"https://site.api.espn.com/apis/site/v2/sports/soccer/{league_id}/summary"
    params = {'event': event_id}

    try:
        response = requests.get(detail_url, params=params, timeout=10)
        if response.status_code == 200:
            return response.json()
    except Exception as e:
        print(f"      ⚠️ Detail fetch error: {str(e)[:60]}")

    return None


def extract_match_context(event, league_id):
    """Extract ALL useful context from ESPN API response"""

    context = {
        'basic_info': {},
        'score': {},
        'events': [],
        'statistics': {},
        'records': {},
        'form': {},
        'commentary': [],
        'article': '',
    }

    # Basic info
    context['basic_info'] = {
        'event_id': event.get('id', ''),
        'name': event.get('name', ''),
        'date': event.get('date', ''),
        'status': event.get('status', {}).get('type', {}).get('description', 'Unknown')
    }

    comp = event.get('competitions', [{}])[0]
    competitors = comp.get('competitors', [])

    if len(competitors) < 2:
        return context

    # Teams
    home_comp = next((c for c in competitors if c.get('homeAway') == 'home'), competitors[0])
    away_comp = next((c for c in competitors if c.get('homeAway') == 'away'), competitors[1])

    home_team = home_comp.get('team', {}).get('displayName', 'Unknown')
    away_team = away_comp.get('team', {}).get('displayName', 'Unknown')

    context['basic_info']['home_team'] = home_team
    context['basic_info']['away_team'] = away_team

    # Score
    home_score = home_comp.get('score', 'N/A')
    away_score = away_comp.get('score', 'N/A')

    context['score'] = {
        'home': home_score,
        'away': away_score,
        'display': f"{home_team} {home_score} - {away_score} {away_team}"
    }

    # Match events (goals, cards)
    details = comp.get('details', [])
    for detail in details:
        event_type = detail.get('type', {}).get('text', 'Unknown')
        clock = detail.get('clock', {}).get('displayValue', 'Unknown')
        team_id = detail.get('team', {}).get('id', '')

        team_name = home_team if str(home_comp.get('team', {}).get('id')) == str(team_id) else away_team

        athletes = detail.get('athletesInvolved', [])
        player = athletes[0].get('displayName', 'Unknown') if athletes else 'Unknown'

        context['events'].append({
            'type': event_type,
            'time': clock,
            'team': team_name,
            'player': player,
            'is_goal': detail.get('scoringPlay', False)
        })

    # Statistics
    home_stats = home_comp.get('statistics', [])
    away_stats = away_comp.get('statistics', [])

    context['statistics']['home'] = {stat['name']: stat['displayValue'] for stat in home_stats}
    context['statistics']['away'] = {stat['name']: stat['displayValue'] for stat in away_stats}

    # Records
    home_records = home_comp.get('records', [])
    away_records = away_comp.get('records', [])

    if home_records:
        context['records']['home'] = home_records[0].get('summary', 'N/A')
    if away_records:
        context['records']['away'] = away_records[0].get('summary', 'N/A')

    # Form
    context['form']['home'] = home_comp.get('form', 'N/A')
    context['form']['away'] = away_comp.get('form', 'N/A')

    # Fetch detailed data
    event_id = event.get('id', '')
    if event_id:
        detail_data = fetch_match_details(event_id, league_id)

        if detail_data:
            # Commentary
            if 'commentary' in detail_data and isinstance(detail_data['commentary'], list):
                for item in detail_data['commentary'][:15]:
                    if isinstance(item, dict) and 'text' in item:
                        context['commentary'].append({
                            'time': item.get('time', {}).get('displayValue', ''),
                            'text': item.get('text', '')
                        })

            # Article
            if 'article' in detail_data:
                article = detail_data['article']
                if isinstance(article, dict) and 'story' in article:
                    # Strip HTML tags
                    import re
                    story = article['story']
                    story = re.sub('<[^<]+?>', '', story)  # Remove HTML
                    context['article'] = story[:1500]

    return context


def format_context_for_ai(context):
    """Format extracted context into readable text for AI"""

    output = []
    basic = context['basic_info']
    status = basic.get('status', 'Unknown')

    output.append(f"MATCH: {basic.get('home_team')} vs {basic.get('away_team')}")
    output.append(f"STATUS: {status}")
    output.append(f"DATE: {basic.get('date')}")

    # Only show score if match is finished
    is_finished = status in ['Full Time', 'FT', 'Final', 'STATUS_FINAL']

    if is_finished and context['score']['home'] != 'N/A':
        output.append(f"\nFINAL SCORE: {context['score']['display']}")

    # Season records
    if context['records'].get('home'):
        output.append(f"\nCURRENT SEASON RECORDS:")
        output.append(f"  {basic.get('home_team')}: {context['records'].get('home')}")
        output.append(f"  {basic.get('away_team')}: {context['records'].get('away')}")

    # Only include match events if finished
    if is_finished and context['events']:
        output.append(f"\nMATCH EVENTS:")
        for event in context['events'][:10]:
            emoji = "⚽" if event['is_goal'] else ("🟨" if "Yellow" in event['type'] else "🟥" if "Red" in event['type'] else "")
            output.append(f"  {emoji} {event['time']}: {event['player']} ({event['team']}) - {event['type']}")

    # Only include statistics if finished
    if is_finished and context['statistics'].get('home'):
        output.append(f"\nKEY STATISTICS:")

        stat_keys = ['possessionPct', 'totalShots', 'shotsOnTarget', 'foulsCommitted']

        for key in stat_keys:
            home_val = context['statistics']['home'].get(key, 'N/A')
            away_val = context['statistics']['away'].get(key, 'N/A')

            if home_val != 'N/A' and away_val != 'N/A':
                stat_name = key.replace('Pct', '%').replace('total', '').replace('Committed', '')
                output.append(f"  {stat_name}: {home_val} vs {away_val}")

    # Only include commentary if finished
    if is_finished and context['commentary']:
        output.append(f"\nCOMMENTARY HIGHLIGHTS:")
        for comm in context['commentary'][:8]:
            if comm['text']:
                output.append(f"  [{comm['time']}] {comm['text'][:120]}")

    # Only include article if finished
    if is_finished and context['article']:
        output.append(f"\nMATCH REPORT EXCERPT:")
        output.append(f"  {context['article'][:600]}")

    return "\n".join(output)

# ============================================================================
# NEWS ARTICLE SCRAPING (RSS FEEDS)
# ============================================================================

RSS_FEEDS = {
    'BBC Sport': 'http://feeds.bbci.co.uk/sport/football/rss.xml',
    'Sky Sports': 'https://www.skysports.com/rss/12040',
    'The Guardian': 'https://www.theguardian.com/football/rss',
}

def scrape_news_articles():
    """Get latest football news from RSS feeds"""

    all_articles = []

    print("📰 Fetching news articles...\n")

    for source_name, feed_url in RSS_FEEDS.items():
        print(f"   📡 {source_name}...")

        try:
            feed = feedparser.parse(feed_url)

            if not feed.entries:
                print(f"      ⚠️ No entries\n")
                continue

            for entry in feed.entries[:10]:
                title = entry.get('title', 'No title')
                link = entry.get('link', '')
                description = entry.get('summary', entry.get('description', ''))

                # Clean HTML from description
                if description:
                    soup = BeautifulSoup(description, 'html.parser')
                    description = soup.get_text(strip=True)

                # Get date
                published = entry.get('published', 'Unknown date')
                try:
                    if hasattr(entry, 'published_parsed') and entry.published_parsed:
                        dt = datetime(*entry.published_parsed[:6])
                        published = dt.strftime('%Y-%m-%d %H:%M')
                except:
                    pass

                if len(title) < 10 or not link:
                    continue

                if any(a['url'] == link for a in all_articles):
                    continue

                all_articles.append({
                    'type': 'article',
                    'source': source_name,
                    'headline': title,
                    'url': link,
                    'preview': description[:150] if description else '',
                    'published': published,
                    'full_context': None  # Will fill if user selects
                })

            print(f"      ✅ {len([a for a in all_articles if a['source'] == source_name])} articles\n")

        except Exception as e:
            print(f"      ❌ Error: {str(e)[:50]}\n")

        time.sleep(0.5)

    return all_articles


def scrape_article_body(url):
    """Fetch full article text"""

    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
    }

    print(f"   📄 Fetching article body...")

    try:
        response = requests.get(url, headers=headers, timeout=10)

        if response.status_code != 200:
            return None

        soup = BeautifulSoup(response.content, 'html.parser')

        # Try multiple selectors
        article_body = (
            soup.find('article') or
            soup.find('div', {'data-component': 'text-block'}) or
            soup.find('div', class_='article-body-commercial-selector') or
            soup.find('div', {'itemprop': 'articleBody'}) or
            soup.find('div', class_='sdc-article-body') or
            soup.find('div', class_='article__body')
        )

        if not article_body:
            return None

        paragraphs = article_body.find_all('p')

        article_text = []
        skip_phrases = ['cookie', 'subscribe', 'sign up', 'follow us', 'read more']

        for p in paragraphs:
            text = p.get_text(strip=True)
            if any(phrase in text.lower() for phrase in skip_phrases):
                continue
            if len(text) < 30:
                continue
            article_text.append(text)

        full_text = '\n\n'.join(article_text)

        headline = soup.find('h1')
        headline_text = headline.get_text(strip=True) if headline else 'Unknown'

        if len(full_text) < 200:
            return None

        print(f"      ✅ Extracted {len(full_text)} chars\n")

        return f"""SOURCE: News Article
HEADLINE: {headline_text}
URL: {url}

ARTICLE CONTENT:
{full_text[:2000]}"""

    except Exception as e:
        print(f"      ❌ Error: {str(e)[:50]}\n")
        return None


def scrape_all_matches_for_selection():
    """Get ALL matches in 2-day window and let user select"""
    all_matches = []

    today = datetime.now()
    start_date = (today - timedelta(days=1)).strftime('%Y%m%d')  # Yesterday
    end_date = (today + timedelta(days=1)).strftime('%Y%m%d')    # Tomorrow

    print(f"🔍 Fetching ALL matches from {start_date} to {end_date}...\n")

    leagues = {
        'eng.1': 'Premier League',
        'esp.1': 'La Liga',
        'ger.1': 'Bundesliga',
        'ita.1': 'Serie A',
        'fra.1': 'Ligue 1',
        'uefa.champions': 'Champions League',
        'eng.fa': 'FA Cup',
        'eng.league_cup': 'EFL Cup (Carabao)',
        'uefa.europa': 'Europa League',
        'uefa.europa.conf': 'Conference League',  # ← Added comma here
        'fifa.friendly': 'International Friendlies',
        'uefa.nations': 'Nations League',
        'conmebol.america': 'Copa America',
        'concacaf.gold': 'Gold Cup',
        'caf.afcon': 'African Cup of Nations',

    }


    for league_id, league_name in leagues.items():
        print(f"🔄 Fetching {league_name}...")

        try:
            url = f"https://site.api.espn.com/apis/site/v2/sports/soccer/{league_id}/scoreboard"
            params = {'dates': f'{start_date}-{end_date}', 'limit': 50}

            response = requests.get(url, params=params, timeout=10)
            if response.status_code != 200:
                print(f"   ⚠️ API error\n")
                continue

            data = response.json()
            events = data.get('events', [])

            if not events:
                print(f"   No matches found\n")
                continue

            for event in events:
                context = extract_match_context(event, league_id)

                home_team = context['basic_info']['home_team']
                away_team = context['basic_info']['away_team']

                if home_team == 'Unknown':
                    continue

                match_key = f"{home_team}_vs_{away_team}"

                # Check for duplicates
                if any(m['match_name'] == match_key for m in all_matches):
                    continue

                formatted_context = format_context_for_ai(context)

                all_matches.append({
                    'league': league_name,
                    'home_team': home_team,
                    'away_team': away_team,
                    'match_time': context['basic_info']['date'],
                    'status': context['basic_info']['status'],
                    'odds': 'N/A',
                    'match_name': match_key.replace(' ', '_'),
                    'event_id': context['basic_info']['event_id'],
                    'full_context': formatted_context
                })

                time.sleep(0.2)

            print(f"   ✅ Found {len([m for m in all_matches if m['league'] == league_name])} matches\n")

        except Exception as e:
            print(f"   ❌ Error: {str(e)[:50]}\n")

    return all_matches


# Run it
print("⚽ Fetching ALL matches...\n")
all_matches = scrape_all_matches_for_selection()
# NEW: Also fetch news articles
print("\n📰 Fetching news articles...\n")
articles = scrape_news_articles()

# NEW: Add type marker to matches
for match in all_matches:
    match['type'] = 'match'

# NEW: Add articles to matches list
for article in articles:
    all_matches.append(article)

if not all_matches:
    print("\n❌ No matches found!")
    matches = []
else:
    # Display all matches with numbers
    print("\n" + "="*70)
    print("📋 AVAILABLE MATCHES:")
    print("="*70 + "\n")

    for i, m in enumerate(all_matches, 1):
        if m.get('type') == 'article':
            print(f"{i}. [ARTICLE - {m['published']}] {m['headline'][:60]}...")
        else:
            print(f"{i}. [{m['league']}] {m['home_team']} vs {m['away_team']} ({m['status']})")

    print("\n" + "="*70)

    # Get user selection
    selection = input("\n📝 Enter match numbers to process (e.g., 1,3,5,7): ")

    # Parse selection
    selected_indices = [int(x.strip()) - 1 for x in selection.split(',') if x.strip().isdigit()]

    # Filter matches
    matches = [all_matches[i] for i in selected_indices if 0 <= i < len(all_matches)]
    # NEW: Fetch article bodies for selected articles
    print("\n🔄 Processing selections...\n")
    for item in matches:
        if item.get('type') == 'article' and not item.get('full_context'):
            print(f"📄 Fetching: {item['headline'][:50]}...")
            item['full_context'] = scrape_article_body(item['url'])
            if not item['full_context']:
                item['full_context'] = f"[Article fetch failed. Using preview: {item.get('preview', '')}]"
            time.sleep(1)

    print(f"\n✅ Selected {len(matches)} items:")
    for m in matches:
        if m.get('type') == 'article':
            print(f"   [ARTICLE] {m['headline'][:60]}...")
        else:
            print(f"   [MATCH] {m['league']}: {m['home_team']} vs {m['away_team']}")

print(f"\n🚀 TOTAL: {len(matches)} matches ready for processing\n")
# Duplicate matches - one set for Groq, one for Gemini
groq_matches = [dict(m, api='groq') for m in matches]
gemini_matches = [dict(m, api='gemini') for m in matches]

all_matches = groq_matches + gemini_matches

print(f"📊 Processing {len(matches)} matches × 2 APIs = {len(all_matches)} total generations\n")
print("\n📋 Processing List:")
for m in matches:
    if m.get('type') == 'article':
        print(f"   [ARTICLE] {m['headline'][:60]}...")
        if m.get('full_context'):
            context_preview = m['full_context'][:150].replace('\n', ' ')
            print(f"      Context: {context_preview}...")
    else:
        print(f"   [MATCH] {m['league']}: {m['home_team']} vs {m['away_team']} - {m['status']}")
        if m.get('full_context'):
            context_preview = m['full_context'][:150].replace('\n', ' ')
            print(f"      Context: {context_preview}...")
print()
print("\n📋 Processing List:")
for m in matches:
    if m.get('type') == 'article':
        print(f"   [ARTICLE] {m['headline'][:60]}...")
    else:
        print(f"   [MATCH] {m['league']}: {m['home_team']} vs {m['away_team']}")


# ============================================================================
# CELL 7: Package Everything into Zips (No API Generation)
# ============================================================================

import zipfile
import io
from google.colab import files

def create_instruction_file(match, mcp1, mcp2, mcp3):
    """Create master instruction file with all MCPs and data embedded"""

    # Get match/article identifier
    if match.get('type') == 'article':
        item_name = match['headline']
        item_info = f"""ARTICLE: {match['headline']}
SOURCE: {match['source']}
PUBLISHED: {match['published']}
URL: {match['url']}"""
    else:
        item_name = f"{match['home_team']} vs {match['away_team']}"
        item_info = f"""MATCH: {match['home_team']} vs {match['away_team']}
LEAGUE: {match['league']}
STATUS: {match['status']}
TIME: {match['match_time']}"""

    instruction = f"""{'='*80}
ANGRY DUDE SCRIPT GENERATOR - STAGED WORKFLOW
{'='*80}

{item_info}

{'='*80}
IMPORTANT: STAGED EXECUTION INSTRUCTIONS
{'='*80}

This file contains 3 stages. You MUST complete them ONE AT A TIME.

After completing each stage:
1. Show me your complete output
2. STOP and WAIT for me to say "proceed"
3. Do NOT move to the next stage until I confirm

{'='*80}
FULL MATCH/ARTICLE CONTEXT DATA
{'='*80}

{match.get('full_context', 'No context available')}

{'='*80}
STAGE 1: EXTRACT TALKING POINTS
{'='*80}

OBJECTIVE: Extract 6-7 roastable angles for the script.

--- MCP 1 COMEDY TECHNIQUES ---
{mcp1.get('rules', 'No rules available')}

--- MCP 1 EXAMPLE ANGLES (Study the style) ---
"""

    # Add MCP1 examples
    for i, example in enumerate(mcp1.get('examples', [])[:2], 1):
        instruction += f"\nEXAMPLE {i}:\n{example}\n"

    instruction += f"""
--- YOUR TASK FOR STAGE 1 ---

Using the COMEDY TECHNIQUES and EXAMPLE ANGLES above, extract 6-7 specific roastable angles from the match/article context data.

"""

    if match.get('type') == 'article':
        instruction += """Focus on:
- Embarrassing moments mentioned in the article
- Controversial quotes
- Ridiculous situations described
- Who's getting roasted in the story
- Drama and conflict points

"""
    elif match.get('status') in ['Full Time', 'FT', 'Final', 'STATUS_FINAL']:
        instruction += """This match is FINISHED. Use the actual match data:
- Real final score
- Actual goal scorers and times
- Real statistics (possession, shots, cards)
- Actual commentary highlights

Focus on:
- Embarrassing moments from the game
- Player disasters (who got cards, who missed sitters)
- Tactical failures evident in the stats
- Controversial incidents from commentary

CRITICAL: Only mention players who appear in the match events above.
If no player names, roast the TEAM not individuals.

"""
    else:
        instruction += """This match is UPCOMING (not played yet). Use context data:
- Current season records and form
- Team struggles this season
- Tactical weaknesses
- What could go wrong

CRITICAL: Do NOT make up match scores or events that haven't happened.
Only mention players if they appear in the data above.
If no player names, roast the TEAM not individuals.

"""

    instruction += """OUTPUT FORMAT: Numbered list with specific, factual angles.

⚠️ STOP HERE AFTER STAGE 1 - Show me your talking points and WAIT for "proceed"

{'='*80}
STAGE 2: WRITE DRAFT SCRIPT
{'='*80}

OBJECTIVE: Write a 200-225 word aggressive comedy script using Stage 1 talking points.

--- MCP 2 STYLE EXAMPLES (MATCH THIS EXACT VOICE) ---
"""

    # Add MCP2 examples
    for i, example in enumerate(mcp2.get('examples', [])[:2], 1):
        instruction += f"\nSTYLE EXAMPLE {i}:\n{example[:1400]}\n"

    instruction += f"""
--- YOUR TASK FOR STAGE 2 ---

Write a script about {item_name} using:
- The talking points you extracted in STAGE 1
- The EXACT style from the examples above

CRITICAL STYLE RULES:
- Short punchy sentences
- CAPS for EMPHASIS on key words
- Aggressive sarcastic roasting - no filter
- Use "bro", "man", "bruv" naturally
- Exaggerate EVERYTHING to ridiculous extremes
- Zero corporate politeness
- Fast energy, no slow build-up
- Nigerian/British slang when natural

TARGET: 200-225 words MAXIMUM (90 second runtime at 150 words/min)

OUTPUT: Just the script text, no extra commentary.

⚠️ STOP HERE AFTER STAGE 2 - Show me your draft script and WAIT for "proceed"

{'='*80}
STAGE 3: POLISH PUNCHLINES
{'='*80}

OBJECTIVE: Enhance the draft script paragraph by paragraph with better punchlines.

--- MCP 3 ENHANCEMENT EXAMPLES ---
"""

    # Add MCP3 examples
    for i, example in enumerate(mcp3.get('examples', [])[:2], 1):
        instruction += f"\nENHANCEMENT EXAMPLE {i}:\n{example[:800]}\n"

    instruction += """
--- YOUR TASK FOR STAGE 3 ---

Take your STAGE 2 draft script and enhance each paragraph using:

ENHANCEMENT TECHNIQUES:
- Add hyper-specific details (exact numbers, player names, brands)
- Exaggerate small truths to absurd extremes
- Double down with absolute confidence
- Make comparisons/analogies more ridiculous
- Tighten pacing - cut filler

PROCESS:
1. Split your Stage 2 script into paragraphs
2. For EACH paragraph, create 3 different enhanced versions
3. Show me all 3 variations for each paragraph
4. I'll pick my favorites

OUTPUT FORMAT:
PARAGRAPH 1:
---VARIATION 1---
[enhanced version]
---VARIATION 2---
[enhanced version]
---VARIATION 3---
[enhanced version]

PARAGRAPH 2:
[same format]

⚠️ STOP HERE AFTER STAGE 3 - Show me all variations and WAIT

{'='*80}
END OF INSTRUCTIONS
{'='*80}

Remember: Complete ONE stage at a time. Show output. Wait for "proceed".
"""

    return instruction


def create_match_zip(match, mcp1, mcp2, mcp3, timestamp):
    """Create a zip file for one match with embedded instructions"""

    # Create filename
    if match.get('type') == 'article':
        safe_name = match['headline'][:40].replace(' ', '_').replace('/', '_').replace(':', '').replace('?', '').replace(',', '')
        zip_name = f"ARTICLE_{safe_name}_{timestamp}.zip"
    else:
        zip_name = f"{match['match_name']}_{timestamp}.zip"

    # Create instruction file content
    instruction_content = create_instruction_file(match, mcp1, mcp2, mcp3)

    # Create zip in memory
    zip_buffer = io.BytesIO()

    with zipfile.ZipFile(zip_buffer, 'w', zipfile.ZIP_DEFLATED) as zipf:
        # Add master instruction file
        zipf.writestr('INSTRUCTIONS_START_HERE.txt', instruction_content)

        # Add a quick reference file
        quick_ref = f"""QUICK START GUIDE
================

1. Attach this entire zip to Claude
2. Ask: "Follow the instructions in INSTRUCTIONS_START_HERE.txt"
3. Claude will do Stage 1 and stop
4. Review the output
5. Say "proceed" to move to Stage 2
6. Repeat for Stage 3

That's it! No copy/pasting needed.
"""
        zipf.writestr('QUICK_START.txt', quick_ref)

    zip_buffer.seek(0)
    return zip_name, zip_buffer.getvalue()


print("\n" + "="*70)
print("📦 PACKAGING MATCHES INTO ZIPS")
print("="*70 + "\n")

timestamp = datetime.now().strftime('%Y%m%d_%H%M')

# Create zips for each match
for i, match in enumerate(matches, 1):
    print(f"📦 Processing {i}/{len(matches)}...")

    if match.get('type') == 'article':
        print(f"   Article: {match['headline'][:50]}...")
    else:
        print(f"   Match: {match['home_team']} vs {match['away_team']}")

    # Create zip
    zip_name, zip_data = create_match_zip(match, mcp1, mcp2, mcp3, timestamp)

    # Save to Drive
    drive_path = os.path.join(OUTPUT_DIR, zip_name)
    with open(drive_path, 'wb') as f:
        f.write(zip_data)
    print(f"   ✅ Saved to Drive: {zip_name}")

    # Auto-download to local PC
    with open(f'/content/{zip_name}', 'wb') as f:
        f.write(zip_data)
    files.download(f'/content/{zip_name}')
    print(f"   ⬇️ Downloaded to PC: {zip_name}\n")

    time.sleep(1)  # Small delay between downloads

print("="*70)
print(f"✅ COMPLETE! Created {len(matches)} zips")
print(f"📂 Saved to Drive: {OUTPUT_DIR}")
print(f"💻 Downloaded to your PC")
print("\n📝 NEXT STEPS:")
print("1. Find the downloaded .zip files on your PC")
print("2. Attach ONE zip to Claude")
print("3. Say: 'Follow the instructions in INSTRUCTIONS_START_HERE.txt'")
print("4. Claude will do Stage 1, show output, and wait")
print("5. Say 'proceed' to move through stages")
print("="*70)